#jdbc:h2:~/test
#spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:~/booking-guide
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.datasource.url=jdbc:mysql://localhost:3306/booking-guide
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Enable Hibernate SQL logging
spring.jpa.show-sql=true

# Format SQL queries (optional, makes it easier to read)
spring.jpa.properties.hibernate.format_sql=true

# Log the SQL with parameters (this is for detailed logging)
spring.jpa.properties.hibernate.generate_statistics=true

# Show Hibernate-generated SQL statements (use for debugging)
logging.level.org.hibernate.SQL=DEBUG

# Log the Hibernate parameter values (optional)
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html